name: 'dbt_first_project'
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
 
models:
  materialized: table